### PR TITLE
23/04/2024 REFACTOR: refactor icon component

### PR DESCRIPTION
**Pull request by habeeb51YA**
what was done: 
Refacactor Icon component

### CODE REVIEW

**Comment by as-abdulsuleiman** [comment]
@habeeb51YA Why do we still have index2tsx and the index where exports are being should be index.ts, not tsx

**Comment by habeeb51YA** [comment]
When I added the index.ts it was causing render issues. And I didn’t want to delete the former index page just incase we need it for something in the future. So I renamed it to index2.tsx, and converted the new one to index.tsx @as-abdulsuleiman

**Comment by as-abdulsuleiman** [comment]
> When I added the index.ts it was causing render issues. And I didn’t want to delete the former index page just incase we need it for something in the future. So I renamed it to index2.tsx, and converted the new one to index.tsx @as-abdulsuleiman

@habeeb51YA change it to index.ts and check what's causing the render issues

**Comment by habeeb51YA** [comment]
I will check it out, I don’t have power at the moment

**Pull request merged**
